/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Default' | 'No Role' | 'Variant 3'
    "dayOfTheWeek"?: string
    "firstTask"?: string
    "secondTask"?: string
    "saveFirstTask"?: string
    "createFirstTask"?: string
    "saveSecondTask"?: string
    "createSecondTask"?: string
}

const ContentCalendarItemFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

ContentCalendarItemFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default ContentCalendarItemFramerComponent

